export const HASH_ALGORITHM = "blake2b512";
export const HASH_ALGORITHM_OUTPUT_LENGTH = 64;

export const SYMMETRIC_ALGORITHM = "chacha20";
export const SYMMETRIC_ALGORITHM_KEY_LENGTH = 32;
export const SYMMETRIC_ALGORITHM_IV_LENGTH = 16;

export const AUTHENTICATED_SYMMETRIC_ALGORITHM = "chacha20-poly1305";
export const AUTHENTICATED_SYMMETRIC_ALGORITHM_KEY_LENGTH = 32;
export const AUTHENTICATED_SYMMETRIC_ALGORITHM_IV_LENGTH = 12;
export const AUTHENTICATED_SYMMETRIC_ALGOTITHM_TAG_LENGTH = 16;

export const KEY_EXCHANGE_ALGORITHM = "x25519";
export const KEY_EXCHANGE_ALGORITHM_PUBLIC_KEY_LENGTH = 32;
export const KEY_EXCHANGE_ALGORITHM_PRIVATE_KEY_LENGTH = 32;
export const KEY_EXCHANGE_ALGORITHM_SHARED_SECRET_LENGTH = 32;

export const SIGNATURE_ALGORITHM = "ed25519";
export const SIGNATURE_ALGORITHM_PUBLIC_KEY_LENGTH = 32;
export const SIGNATURE_ALGORITHM_PRIVATE_KEY_LENGTH = 32;
export const SIGNATURE_ALGORITHM_SIGNATURE_LENGTH = 64;